
CREATE TABLE public.PRATIQUES_ALIMENTAIRES (
                ID_PRATIQUE BIGINT NOT NULL,
                NOM VARCHAR(100) NOT NULL,
                DESCRIPTIF VARCHAR(1000),
                CONSTRAINT id_pratique PRIMARY KEY (ID_PRATIQUE)
);


CREATE TABLE public.CODES_COULEURS (
                CODE_COULEUR VARCHAR(1) NOT NULL,
                LIBELLE VARCHAR(10) NOT NULL,
                DESCRIPTIF VARCHAR(500),
                CONSTRAINT code_couleur PRIMARY KEY (CODE_COULEUR)
);


CREATE TABLE public.ADDITIFS (
                CODE_ADDITIF VARCHAR(5) NOT NULL,
                NOM_ADDITIF VARCHAR(100) NOT NULL,
                DESCRIPTIF VARCHAR(500),
                CONSTRAINT code_additif PRIMARY KEY (CODE_ADDITIF)
);


CREATE TABLE public.ADDITIFS_PRATIQUES (
                CODE_ADDITIF VARCHAR(5) NOT NULL,
                ID_PRATIQUE BIGINT NOT NULL,
                CODE_COULEUR VARCHAR(1) NOT NULL,
                CONSTRAINT code_additif_id_pratique PRIMARY KEY (CODE_ADDITIF, ID_PRATIQUE)
);


CREATE INDEX additifs_pratiques_idx
 ON ADDITIFS_PRATIQUES
 ( CODE_COULEUR );

CREATE TABLE public.INGREDIENTS (
                ID_INGREDIENT BIGINT NOT NULL,
                NOM VARCHAR(100) NOT NULL,
                DESCRIPTIF VARCHAR(500),
                CONSTRAINT id_ingredient PRIMARY KEY (ID_INGREDIENT)
);


CREATE INDEX ingredients_idx
 ON INGREDIENTS
 ( ID_INGREDIENT ASC );

CREATE TABLE public.PRODUITS (
                CODE_EAN VARCHAR(13) NOT NULL,
                NOM VARCHAR(100) NOT NULL,
                DESCRIPTIF VARCHAR(1000),
                CODE_COULEUR VARCHAR(1) NOT NULL,
                ID_CATEGORIE BIGINT NOT NULL,
                VISIBLE BOOLEAN DEFAULT FALSE NOT NULL,
                CONSTRAINT code_ean PRIMARY KEY (CODE_EAN)
);


CREATE INDEX produits_idx
 ON PRODUITS
 ( VISIBLE );
 CREATE INDEX categories_idx
 ON PRODUITS
 ( ID_CATEGORIE ASC );

CREATE TABLE public.PRODUITS_INGREDIENTS (
                CODE_EAN VARCHAR(13) NOT NULL,
                ID_INGREDIENT BIGINT NOT NULL,
                COMPOSITION_100g NUMERIC(3,2) NOT NULL,
                CONSTRAINT code_ean_id_ingredient PRIMARY KEY (CODE_EAN, ID_INGREDIENT)
);


CREATE TABLE public.PRODUITS_ADDITIFS (
                CODE_EAN VARCHAR(13) NOT NULL,
                CODE_ADDITIF VARCHAR(5) NOT NULL,
                CONSTRAINT code_ean_code_additifs PRIMARY KEY (CODE_EAN, CODE_ADDITIF)
);


CREATE SEQUENCE categories_id_categorie_seq;

CREATE TABLE public.CATEGORIES (
                ID_CATEGORIE BIGINT NOT NULL DEFAULT nextval('categories_id_categorie_seq'),
                NOM VARCHAR(100) NOT NULL,
                DESCRIPTIF VARCHAR(500),
                CONSTRAINT id_categorie PRIMARY KEY (ID_CATEGORIE)
);


ALTER SEQUENCE categories_id_categorie_seq OWNED BY CATEGORIES.ID_CATEGORIE;


ALTER TABLE ADDITIFS_PRATIQUES ADD CONSTRAINT pratiques_alimentaires_additifs_pratiques_fk
FOREIGN KEY (ID_PRATIQUE)
REFERENCES PRATIQUES_ALIMENTAIRES (ID_PRATIQUE)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE ADDITIFS_PRATIQUES ADD CONSTRAINT codes_couleurs_additifs_pratiques_fk
FOREIGN KEY (CODE_COULEUR)
REFERENCES CODES_COULEURS (CODE_COULEUR)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE PRODUITS ADD CONSTRAINT codes_couleurs_produits_fk
FOREIGN KEY (CODE_COULEUR)
REFERENCES CODES_COULEURS (CODE_COULEUR)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE ADDITIFS_PRATIQUES ADD CONSTRAINT additifs_additifs_pratiques_fk
FOREIGN KEY (CODE_ADDITIF)
REFERENCES ADDITIFS (CODE_ADDITIF)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE PRODUITS_ADDITIFS ADD CONSTRAINT additifs_produits_additifs_fk
FOREIGN KEY (CODE_ADDITIF)
REFERENCES ADDITIFS (CODE_ADDITIF)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE PRODUITS_INGREDIENTS ADD CONSTRAINT ingredients_produits_ingredients_fk
FOREIGN KEY (ID_INGREDIENT)
REFERENCES INGREDIENTS (ID_INGREDIENT)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE PRODUITS ADD CONSTRAINT categories_produits_fk
FOREIGN KEY (ID_CATEGORIE)
REFERENCES CATEGORIES (ID_CATEGORIE)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE PRODUITS_ADDITIFS ADD CONSTRAINT produits_produits_additifs_fk
FOREIGN KEY (CODE_EAN)
REFERENCES PRODUITS (CODE_EAN)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE PRODUITS_INGREDIENTS ADD CONSTRAINT produits_produits_ingredients_fk
FOREIGN KEY (CODE_EAN)
REFERENCES PRODUITS (CODE_EAN)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;